[package]
name = "rust_basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "2.1.0"
serde = {version="1.0.206", features=["derive"]}
serde_json = "1.0.124"
ureq = "2.10.1"
